name: auth_manager
description: "Example app for Auth Ninja SDK"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  auth_ninja_sdk:
    path: ../

  # auth_ninja_sdk: git: url: https://github.com/McMaurice/auth-ninja-sdk 
  # ref: main


  flutter_riverpod: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.1.1
  google_fonts: ^6.3.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
# To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/defaultimage.png